### ISSUE TITLE
Allowing empty returns wrong results 

### ISSUE THREAD

**Issue by losmi83** [RumbleDB/rumble#760]
Several issues with allowing empty on the master:

1) Wrong result with local collections:

```
let $stores := [  { "store number" : 1, "state" : "MA" } ]
let $nations := [  { "name": "US", "state": "MA" }, { "name": "US", "state": "CA" } ]
for $nation in $nations[], $store allowing empty in $stores[]
    [ $$.state eq $nation.state ] 
return { "name": $nation.state, "stores": $store."store number" }
```
Output: 
```
{ "name" : "MA", "stores" : 1 }
{ "name" : "CA", "stores" : null }
{ "name" : "CA", "stores" : null }
{ "name" : "CA", "stores" : null }
...
{ "name" : "CA", "stores" : null }
Warning! The output sequence contains 9223372036854775807 items but its materialization was capped at 200 items. This value can be configured with the --result-size parameter at startup
```

2) Infinite loop with local collections:
```
let $stores :=[  { "store number" : 1, "state" : "MA" } ]
let $nations := [  { "name": "US", "state": "MA" }, { "name": "US", "state": "CA" } ]
let $join := 
    for $nation in $nations[], $store allowing empty in $stores[]
        [ $$.state eq $nation.state ] 
    return { "name": $nation.state, "stores": $store."store number" }
return [$join]
```

3) Wrong result with local + distributed collections:
```
let $stores := parallelize([  { "store number" : 1, "state" : "MA" } ])
let $nations := [  { "name": "US", "state": "MA" }, { "name": "US", "state": "CA" } ]
for $nation in $nations[], $store allowing empty in $stores[]
    [ $$.state eq $nation.state ] 
return { "name": $nation.state, "stores": $store."store number" }
```

Output:
```
{ "name" : "MA", "stores" : null }
{ "name" : "CA", "stores" : null }
```
The result is correct, however, when nations is distributed and stores is local.

4) Allowing empty with two distributed collections not supported

```
let $stores := parallelize([  { "store number" : 1, "state" : "MA" } ])
let $nations := parallelize([  { "name": "US", "state": "MA" }, { "name": "US", "state": "CA" } ])
for $nation in $nations[], $store allowing empty in $stores[]
    [ $$.state eq $nation.state ] 
return { "name": $nation.state, "stores": $store."store number" }
```

Output:

```
⚠️  ️There was an error.
A for clause expression cannot produce a big sequence of items for a big number of tuples, as this would lead to a data flow explosion.
```

**Comment by ghislainfourny** [comment]
Thanks a lot! This is immensely appreciated and catches two issues that are now fixed.

Points 1. 2. and 3. are now fixed in the master.

Point 4. creates a parallel job inside a parallel job, which Spark does not allow. We choose to throw an error here rather than attempt a materialization.

It is on our agenda to keep pushing the optimization frontier further, based on such feedback. In this case, we could try to auto-detect query patterns that look like joins and push them down to Spark accordingly.

**Comment by ghislainfourny** [comment]
Point 4 is now implemented as well -- you just need to add a "return" after the two lets to help Rumble recognize its ability to pushdown it as a join to Spark. In the future, we'll add one more optimization to automatically add it.

**Comment by losmi83** [comment]
Thanks for your prompt replies. I still have problems with point 4, the following code gets stuck again.

```
let $lineitem := parallelize(csv-file("file:///dataset/lineitem.csv", { "header": true, "inferSchema": true, "sep": "|" }), 100)
let $orders := parallelize(csv-file("file:///dataset/orders.csv", { "header": true, "inferSchema": true, "sep": "|" }), 100)
return 
      for $o in $orders, $l allowing empty in $lineitem  $$.l_orderkey eq $o.o_orderkey ] 
      return { "orderkey": $o.o_orderkey, qty": $l.l_quantity } 
```
The collections are relatively small TPC-H tables with 60K and 15K tuples. The same problem appears without parallelize.

**Comment by ghislainfourny** [comment]
Thanks for giving it a try and for letting us know, @losmi83. Would it be possible to share the two CSV files with us so we can reproduce?

Also in your query, a "[" is missing around the predicate.

**Comment by losmi83** [comment]
Here is the test dataset.

[test_dataset.zip](https://github.com/RumbleDB/rumble/files/5175204/test_dataset.zip)

**Comment by ghislainfourny** [comment]
Thank you, @losmi83. Your feedback is highly appreciated.

I fixed your query like so (there was also a missing " before qty):

let $lineitem :=csv-file("/Users/ghislain/Downloads/test_dataset/lineitem.csv", { "header": true, "inferSchema": true, "sep": "|" })
let $orders :=csv-file("/Users/ghislain/Downloads/test_dataset/orders.csv", { "header": true, "inferSchema": true, "sep": "|" })
return 
  for $o in $orders, $l allowing empty in $lineitem  [$$.l_orderkey eq $o.o_orderkey ] 
  return { "orderkey": $o.o_orderkey, "qty": $l.l_quantity } 

For now, Spark seems to do a full cartesian product in this case.

I have however pushed a fixed, today, that makes sure Spark performs an efficient join at least if this is an inner join, so this query works on my side in 15 seconds.

let $lineitem :=csv-file("/Users/ghislain/Downloads/test_dataset/lineitem.csv", { "header": true, "inferSchema": true, "sep": "|" })
let $orders :=csv-file("/Users/ghislain/Downloads/test_dataset/orders.csv", { "header": true, "inferSchema": true, "sep": "|" })
return 
  for $o in $orders, $l in $lineitem  [$$.l_orderkey eq $o.o_orderkey ] 
  return { "orderkey": $o.o_orderkey, "qty": $l.l_quantity } 

For the left outer join (allowing empty), I'll try to see if I find a way to have Spark avoid computing a full cartesian product as well.

**Comment by ghislainfourny** [comment]
Left outer joins are now support with let clauses.

This makes it possible to use with a subsequent for-clause with an allowing empty like so:

let $lineitems := csv-file("test_dataset/lineitem.csv", { "header": true, "inferSchema": true, "sep": "|" })
let $orders := csv-file("test_dataset/orders.csv", { "header": true, "inferSchema": true, "sep": "|" })
return
  for $o in $orders
  let $li := $lineitems  [$$.l_orderkey eq $o.o_orderkey ]
  for $l allowing empty in $li
  return { "key" : $o.o_orderkey, qty: $l.l_quantity }

**Comment by ghislainfourny** [comment]
Another quick update: Rumble now also detects joins if the predicate is in a where clause.

let $lineitems := csv-file("test_dataset/lineitem.csv", { "header": true, "inferSchema": true, "sep": "|" })
let $orders := csv-file("test_dataset/orders.csv", { "header": true, "inferSchema": true, "sep": "|" })
return
for $o in $orders
for $l in $lineitems
where $l.l_orderkey eq $o.o_orderkey
return { "key" : $o.o_orderkey, qty: $l.l_quantity }

**Comment by ghislainfourny** [comment]
@losmi83 do you consider that this issue is addressed?

**Comment by losmi83** [comment]
I've tried to re-run your example from above on with Rumble 1.11 and Spark 3.1.1.

```
let $lineitems := csv-file("/test_dataset/lineitem.csv", { "header": true, "inferSchema": true, "sep": "|" })
let $orders := csv-file("/test_dataset/orders.csv", { "header": true, "inferSchema": true, "sep": "|" })
return
for $o in $orders
let $l := $lineitems [$$.l_orderkey eq $o.o_orderkey ]
return {| $o, { "lineitems": [ $l ] } |}
```

> ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7 used for parser compilation does not match the current runtime version 4.8
> 
> [INFO] Rumble detected an equi-join in the left clause.
> [ERROR] An error has occurred: org.apache.spark.SparkException: Job aborted due to stage failure: Task 69 in stage 5.0 failed 1 times, most recent failure: Lost task 69.0 in stage 5.0 (TID 5) (192.168.0.18 executor driver): org.apache.spark.SparkException: Failed to execute user defined function(UDFRegistration$$Lambda$2767/49534413: (array<struct<l_orderkey:int,l_partkey:int,l_suppkey:int,l_linenumber:int,l_quantity:int,l_extendedprice:double,l_discount:double,l_tax:double,l_returnflag:string,l_linestatus:string,l_shipdate:int,l_commitdate:int,l_receiptdate:int,l_shipinstruct:string,l_shipmode:string,l_comment:string>>) => binary)
> 	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
> 	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
> 	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:755)
> 	at org.apache.spark.sql.execution.SparkPlan.$anonfun$getByteArrayRdd$1(SparkPlan.scala:345)
> 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2(RDD.scala:898)
> 	at org.apache.spark.rdd.RDD.$anonfun$mapPartitionsInternal$2$adapted(RDD.scala:898)
> 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
> 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
> 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
> 	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
> 	at org.apache.spark.scheduler.Task.run(Task.scala:131)
> 	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:497)
> 	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1439)
> 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:500)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: java.lang.ClassCastException: org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema cannot be cast to [B
> 	at org.rumbledb.runtime.flwor.FlworDataFrameUtils.deserializeWrappedParameters(FlworDataFrameUtils.java:594)
> 	at org.rumbledb.runtime.flwor.udfs.GroupClauseSerializeAggregateResultsUDF.call(GroupClauseSerializeAggregateResultsUDF.java:49)
> 	at org.rumbledb.runtime.flwor.udfs.GroupClauseSerializeAggregateResultsUDF.call(GroupClauseSerializeAggregateResultsUDF.java:1)
> 	at org.apache.spark.sql.UDFRegistration.$anonfun$register$352(UDFRegistration.scala:777)
> 	... 17 more
> 
> Driver stacktrace:
> We should investigate this 🙈. Please contact us or file an issue on GitHub with your query. 
> Link: https://github.com/RumbleDB/rumble/issues
> rumble$ 
>
